### ISSUE TITLE
chore: Confirm Flutter 3.24.0 and Dart 3.5 Support

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/flutter_web_preloader#25]
**Description**

With the release of Flutter 3.24.0 and Dart 3.5 some things are breaking. Need to review the package and make any necessary fixes.

**Requirements**

- [ ] Package works correctly on Flutter 3.24.0 and Dart 3.5

**Comment by alestiago** [comment]
We should consider https://docs.flutter.dev/platform-integration/web/initialization and update accordingly.

**Comment by alestiago** [comment]
Another to consider: https://docs.flutter.dev/release/breaking-changes/asset-manifest-dot-json

**Comment by alestiago** [comment]
Waiting for a release since #26 was merged.
